import { collectDefaultMetrics, Counter, Histogram, Registry } from "prom-client";

/**
 * Prometheus metrics. A dedicated Registry (not the global default) keeps
 * tests isolated and lets us run multiple app instances in-process.
 */
export function createMetrics() {
  const registry = new Registry();
  registry.setDefaultLabels({ service: "troopers-api" });
  collectDefaultMetrics({ register: registry });

  const httpRequestsTotal = new Counter({
    name: "http_requests_total",
    help: "Total HTTP requests",
    labelNames: ["method", "route", "status"] as const,
    registers: [registry],
  });

  const httpRequestDuration = new Histogram({
    name: "http_request_duration_seconds",
    help: "HTTP request latency",
    labelNames: ["method", "route", "status"] as const,
    // Buckets tuned for the < 1.5s p95 target in PRD NFR-3.
    buckets: [0.01, 0.05, 0.1, 0.25, 0.5, 1, 1.5, 3],
    registers: [registry],
  });

  const remindersGenerated = new Counter({
    name: "reminders_generated_total",
    help: "Reminder instances generated by the reminders engine",
    labelNames: ["type"] as const,
    registers: [registry],
  });

  return { registry, httpRequestsTotal, httpRequestDuration, remindersGenerated };
}

export type Metrics = ReturnType<typeof createMetrics>;
